; Listing generated by Microsoft (R) Optimizing Compiler Version 19.11.25508.2 

	TITLE	C:\Users\Thomas\source\repos\Projet_IA\Buckland_Chapter7 to 10_Raven\goals\Goal_SayPhrase.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

END
