; Listing generated by Microsoft (R) Optimizing Compiler Version 19.11.25547.0 

	TITLE	D:\Math Visual Studio\IA_ProjRaven\Buckland_Chapter7 to 10_Raven\goals\Goal_SayPhrase.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

END
